// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhigPf0W6n5Ojnss_i0tQeNDCWGRRjTm0',
    appId: '1:231523129407:web:aa27ce50273706b326808a',
    messagingSenderId: '231523129407',
    projectId: 'trackdriver-67440',
    authDomain: 'trackdriver-67440.firebaseapp.com',
    storageBucket: 'trackdriver-67440.appspot.com',
    measurementId: 'G-0MD6E0NB2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvqfyyaKxJixZgfCn9YeHn9WkSGcw59Ts',
    appId: '1:231523129407:android:fad32e233710037b26808a',
    messagingSenderId: '231523129407',
    projectId: 'trackdriver-67440',
    storageBucket: 'trackdriver-67440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfigXDUnGJu2T1KHnxkaS6THTBKAX8yrE',
    appId: '1:231523129407:ios:4662f3a1f7b0398a26808a',
    messagingSenderId: '231523129407',
    projectId: 'trackdriver-67440',
    storageBucket: 'trackdriver-67440.appspot.com',
    iosBundleId: 'com.example.busTrack1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfigXDUnGJu2T1KHnxkaS6THTBKAX8yrE',
    appId: '1:231523129407:ios:b268875e45d8d65926808a',
    messagingSenderId: '231523129407',
    projectId: 'trackdriver-67440',
    storageBucket: 'trackdriver-67440.appspot.com',
    iosBundleId: 'com.example.busTrack1.RunnerTests',
  );
}
